title: Garet's Basic Portfolio of Coding Projects
description: This portfolio ranges from straightforward to intermediate-skilled coding projects, showcasing an understanding of analysis and cybersecurity fundamentals.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
