title: Garet's Basic Portfolio of Coding Projects
description: My portfolio ranges from straightforward to intermediate-skilled coding projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight
